version: "3.9"

volumes:
  dbdata:

services:
  db:
    image: postgres:16-alpine
    container_name: nwu-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nwupoll}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-nwupoll}"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    image: node:20-bullseye-slim
    container_name: nwu-api
    working_dir: /app
    volumes:
      - ./apps/api:/app:cached
      - ./apps/api/node_modules:/app/node_modules
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-nwupoll}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm install && npx prisma generate && npm run dev"
